# .github/workflows/main_sqlbot.yml
name: Build and deploy Python app to Azure Web App - sqlbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      # Fix the import issue before deployment
      - name: Fix import issues
        run: |
          echo "Fixing import issues..."
          # Fix any 'good.' imports
          find . -name "*.py" -type f -exec sed -i 's/from good\.query_validator/from query_validator/g' {} \;
          find . -name "*.py" -type f -exec sed -i 's/from good\./from /g' {} \;
          echo "Import fixes applied"
          
      - name: Verify critical files exist
        run: |
          echo "Checking critical files..."
          for file in app.py teams_sql_bot.py azure_openai_sql_translator.py query_validator.py autonomous_sql_explorer.py token_limiter.py; do
            if [ -f "$file" ]; then
              echo "✓ $file exists"
            else
              echo "❌ $file missing!"
              exit 1
            fi
          done
          echo "All critical files present"
          
      - name: Zip artifact for deployment
        run: |
          echo "Creating deployment package..."
          # Exclude test files and other unnecessary items
          zip release.zip ./* -r \
            -x "venv/*" \
            -x ".git/*" \
            -x ".github/*" \
            -x "__pycache__/*" \
            -x "*.pyc" \
            -x "test_*.py" \
            -x "debug_*.py" \
            -x "*.md" \
            -x ".gitignore" \
            -x "*.txt" 
          
          # Add back requirements.txt (it's needed!)
          zip release.zip requirements.txt
          
          echo "Deployment package created"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sqlbot'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2CAC3A2977004BBCA8D9105E09759C8D }}