# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - sqlbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Create startup script
        run: |
          cat > startup.sh << 'EOF'
          #!/bin/bash
          echo "Starting SQL Assistant Bot..."
          cd /home/site/wwwroot
          
          # Set up environment
          export LD_LIBRARY_PATH="/tmp/oryx/platforms/python/3.11.12/lib:$LD_LIBRARY_PATH"
          export PYTHONPATH="/home/site/wwwroot/antenv/lib/python3.11/site-packages:/home/site/wwwroot:$PYTHONPATH"
          
          # Try to find Python in different locations
          if [ -f "/tmp/oryx/platforms/python/3.11.12/bin/python3.11" ]; then
              PYTHON="/tmp/oryx/platforms/python/3.11.12/bin/python3.11"
          elif [ -f "/home/site/wwwroot/antenv/bin/python3.11" ]; then
              export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
              PYTHON="/home/site/wwwroot/antenv/bin/python3.11"
          else
              PYTHON="python"
          fi
          
          # Start the application
          echo "Using Python: $PYTHON"
          exec $PYTHON -m gunicorn --bind 0.0.0.0:8000 --worker-class aiohttp.GunicornWebWorker --timeout 600 --workers 1 app:APP
          EOF
          chmod +x startup.sh

      - name: Clean up unnecessary files
        run: |
          # Remove test files and other unnecessary items
          rm -f test_*.py
          rm -rf .git
          rm -rf .github
          rm -f .gitignore
          
      - name: Zip artifact for deployment
        run: |
          # Create deployment package
          zip release.zip ./* -r -x "venv/*" -x ".git/*" -x ".github/*" -x "__pycache__/*" -x "*.pyc"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sqlbot'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2CAC3A2977004BBCA8D9105E09759C8D }}